CREATE TABLE passwd_remind_request (
	id BIGINT (20) NOT NULL AUTO_INCREMENT,
	PASSWORD VARCHAR(60) DEFAULT NULL,
	REQUESTED TIMESTAMP NOT NULL,
	ACTIVATION_TOKEN VARCHAR(128) NOT NULL,
	USER_ID BIGINT (20) NOT NULL,
    VALID BOOLEAN DEFAULT TRUE,
	PRIMARY KEY (id),
	UNIQUE KEY ACTIVATION_TOKEN (ACTIVATION_TOKEN)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

ALTER TABLE passwd_remind_request ADD CONSTRAINT passwd_remind_request_user FOREIGN KEY (USER_ID) REFERENCES user (id);